openapi: 3.0.2
info:
  title: Customers
  version: 1.0.0
  contact:
    name: GEODIS
  description: The Customers Domain Object
tags:
  - name: Synapse Modernization
  - name: ToolHive
servers:
  - url: 'http://localhost:3000'
paths:
  /api/customer/create:
    post:
      tags:
        - Synapse Modernization
      summary: Create Customer
      operationId: post-api-customers-create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerResponseViewModel'
              examples:
                example-1:
                  value:
                    CustomerId: fee63bf3-6cf1-4b7c-8f89-57f658895684
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseCommandResponseViewModel'
      description: Add a new Customer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequestViewModel'
            examples:
              example-1:
                value:
                  CustomerNumber: '123456789'
                  CustomerName: My Customer
                  Address:
                    ContactName: My Contact
                    AddressLine1: 124 Main Street
                    AddessLine2: 'Box #42'
                    AddressLine3: C/O John Smith
                    City: Brentwood
                    State: TN
                    PostalCode: '32027'
                    Country: US
                    Phone: 123-456-7890
                    Email: my.contact@address.com
                  URL: 'https://mysite.org'
                  Logo: 'https://mysite.org/myurl'
                  MarketLine: Manufacturing
                  IsActive: true
                  IsDataRetention: true
                  PersonalRetention: 365
                  OrderRetention: 365
                  MarketLineLeader: MyMarketLineLeader
                  MarketLineOwner: MyMarketLineOwner
                  IsMarketLineAccount: true
        description: Reqeust Body
    parameters: []
  /api/customer/update:
    put:
      tags:
        - Synapse Modernization
      summary: Update Customer
      operationId: put-api-customers-update
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerResponseViewModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
      description: Update a customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerRequestViewModel'
        description: Request Body
  /api/customer/logo/update:
    put:
      summary: Update Customer Logo
      operationId: put-api-customer-logo-update
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerLogoResponseViewModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
      description: Update Customer Logo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerLogoRequestViewModel'
        description: Request body
      tags:
        - Synapse Modernization
        - ToolHive
  /api/customer/logo/create:
    post:
      summary: Create Customer Logo
      operationId: post-api-customer-logo-create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerLogoResponseViewModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
            application/xml:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
      description: 'Create Customer Logo - This is identical to Update Customer Logo, so it is really an alias of Update.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerLogoRequestViewModel'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateCustomerLogoRequestViewModel'
        description: Request body
      tags:
        - Synapse Modernization
        - ToolHive
  /api/customer/logo/delete:
    delete:
      summary: Delete Customer Logo
      operationId: delete-api-customer-logo-delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteCustomerLogoResponseViewModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseCommandResponseViewModel'
      description: Delete Customer Logo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteCustomerLogoRequestViewModel'
        description: Request body
components:
  schemas:
    CreateCustomerRequestViewModel:
      title: CreateCustomerRequest
      description: Create Customer
      x-examples: {}
      allOf:
        - $ref: '#/components/schemas/BaseCommandRequestViewModel'
        - type: object
          properties:
            Name:
              type: string
            Abbreviation:
              type: string
            ContactName:
              type: string
            AddressLine1:
              type: string
            AddressLine2:
              type: string
            AddressLine3:
              type: string
            City:
              type: string
            State:
              type: string
            PostalCode:
              type: string
            Country:
              type: string
            Phone:
              type: string
            Email:
              type: string
            URL:
              type: string
            Logo:
              type: string
            MarketLineId:
              type: string
            IsActive:
              type: boolean
            ActiveDate:
              type: string
            InactiveDate:
              type: string
            IsDataRetention:
              type: boolean
            PersonalRetention:
              type: number
            OrderRetention:
              type: number
            IsMarketLineAccount:
              type: boolean
      x-tags:
        - Synapse Modernization
        - ToolHive
    CreateCustomerResponseViewModel:
      title: CreateCustomerResponse
      x-examples:
        example-1:
          CustomerId: fee63bf3-6cf1-4b7c-8f89-57f658895684
      allOf:
        - $ref: '#/components/schemas/BaseCommandResponseViewModel'
        - type: object
          properties:
            CustomerId:
              type: string
      description: Create Customer Response
      x-tags:
        - Synapse Modernization
        - ToolHive
    UpdateCustomerRequestViewModel:
      title: UpdateCustomerRequest
      allOf:
        - $ref: '#/components/schemas/BaseCommandRequestViewModel'
        - type: object
          properties:
            Id:
              type: string
            Name:
              type: string
            Abbreviation:
              type: string
            ContactName:
              type: string
            AddressLine1:
              type: string
            AddressLine2:
              type: string
            AddressLine3:
              type: string
            City:
              type: string
            State:
              type: string
            PostalCode:
              type: string
            Country:
              type: string
            Phone:
              type: string
            Email:
              type: string
            URL:
              type: string
            Logo:
              type: string
            MarketLineId:
              type: string
            IsActive:
              type: boolean
            ActiveDate:
              type: string
            InactiveDate:
              type: string
            IsDataRetention:
              type: boolean
            PersonalRetention:
              type: number
            OrderRetention:
              type: number
            IsMarketLineAccount:
              type: boolean
      description: Update Customer Request
      x-tags:
        - Synapse Modernization
        - ToolHive
    UpdateCustomerResponseViewModel:
      description: Update Customer Response
      allOf:
        - $ref: '#/components/schemas/BaseCommandResponseViewModel'
        - type: object
          properties:
            IsError:
              type: boolean
            ErrorMessage:
              type:
                - string
                - 'null'
      x-tags:
        - Synapse Modernization
        - ToolHive
      title: ''
    BaseCommandResponseViewModel:
      title: BaseCommandResponseViewModel
      type: object
      properties:
        IsError:
          type: boolean
        ErrorMessage:
          type:
            - string
            - 'null'
      description: Base Command Response
      x-tags:
        - Synapse Modernization
        - ToolHive
    BaseCommandRequestViewModel:
      title: BaseCommandRequestViewModel
      type: object
      description: Base Command Request
      properties:
        UserId:
          type: string
        UserName:
          type: string
        Environment:
          type: string
        ActivityId:
          type:
            - string
            - 'null'
        ParentPageId:
          type:
            - string
            - 'null'
        PageId:
          type:
            - string
            - 'null'
        SessionId:
          type:
            - string
            - 'null'
        Route:
          type:
            - string
            - 'null'
        Equipment:
          type:
            - string
            - 'null'
        AssignmentId:
          type:
            - string
            - 'null'
        DeviceIpV4:
          type:
            - string
            - 'null'
        DeviceIpV6:
          type:
            - string
            - 'null'
        UserAgent:
          type:
            - string
            - 'null'
        Path:
          type:
            - string
            - 'null'
        EpochTime:
          type:
            - string
            - 'null'
        ServerHostName:
          type:
            - string
            - 'null'
        Pid:
          type:
            - string
            - 'null'
        BusinessUnitId:
          type: string
        ApiRequestId:
          type:
            - string
            - 'null'
        AccountId:
          type: string
        Account:
          type: string
        BusinessUnit:
          type: string
        WareHouseId:
          type:
            - string
            - 'null'
      x-tags:
        - Synapse Modernization
        - ToolHive
    UpdateCustomerLogoRequestViewModel:
      allOf:
        - $ref: '#/components/schemas/BaseCommandRequestViewModel'
        - type: object
          properties:
            Id:
              type: string
            Logo:
              type: string
      description: Update Customer Logo Request View Model
      x-tags:
        - Synapse Modernization
        - ToolHive
    UpdateCustomerLogoResponseViewModel:
      title: UpdateCustomerLogoResponseViewModel
      allOf:
        - $ref: '#/components/schemas/BaseCommandResponseViewModel'
        - type: object
          properties:
            IsError:
              type: boolean
            ErrorMessage:
              type:
                - string
                - 'null'
      description: Update Customer Logo Response
      x-tags:
        - Synapse Modernization
        - ToolHive
    DeleteCustomerLogoRequestViewModel:
      title: DeleteCustomerLogoRequestViewModel
      description: Delete Customer Logo Request View Model
      allOf:
        - $ref: '#/components/schemas/BaseCommandRequestViewModel'
        - type: object
          properties:
            Id:
              type: string
      x-tags:
        - Synapse Modernization
        - ToolHive
    DeleteCustomerLogoResponseViewModel:
      title: DeleteCustomerLogoResponseViewModel
      description: Delete Customer Logo Response View Model
      x-tags:
        - Synapse Modernization
        - ToolHive
      allOf:
        - $ref: '#/components/schemas/BaseCommandResponseViewModel'
        - type: object
          properties:
            Id:
              type: string
  securitySchemes: {}
